/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.view;

import lk.edu.ijse.utill.IDGenarator;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.controller.ControllerFactory;
import lk.edu.ijse.controller.custom.BatchController;
import lk.edu.ijse.controller.custom.BatchTransferController;
import lk.edu.ijse.controller.custom.CourseController;
import lk.edu.ijse.controller.custom.DailyCollectionController;
import lk.edu.ijse.controller.custom.PaymentController;
import lk.edu.ijse.controller.custom.RegistrationController;
import lk.edu.ijse.controller.custom.StudentController;
import lk.edu.ijse.dto.BatchDTO;
import lk.edu.ijse.dto.BatchTransferDTO;
import lk.edu.ijse.dto.CourseDTO;
import lk.edu.ijse.dto.DailycollectionDTO;
import lk.edu.ijse.dto.PaymentDTO;
import lk.edu.ijse.dto.RegistrationDTO;
import lk.edu.ijse.dto.StudentDTO;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author epc
 */
public class BatchTransfer extends javax.swing.JFrame {

    private RegistrationController registrationController;
    private CourseController courseController;
    private BatchController batchController;
    private StudentController studentController;
    private BatchTransferController batchTransferController;
    private DailyCollectionController dailyCollectionController;
    private PaymentController paymentController;
    private String prefix;
    private String tableName;
    private String columName;
    private RegistrationDTO registrationDTO=new RegistrationDTO();
    /**
     * Creates new form BatchTransfer
     */
    public BatchTransfer() {
        initComponents();
        setLocationRelativeTo(null);
        registrationController = (RegistrationController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.REGISTRATION);
        dailyCollectionController = (DailyCollectionController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.DAILYCOLLECTION);
        batchTransferController = (BatchTransferController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.BATCHTRANSFER);
        studentController = (StudentController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.STUDENT);
        batchController = (BatchController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.BATCH);
        courseController = (CourseController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.COURSE);
        paymentController = (PaymentController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.PAYMENT);
        Idgent1();
        ViewAll();
        setTime();
        setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HOME_TIME1 = new javax.swing.JLabel();
        HOME_TIME = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TxtTo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtBtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtBtFee = new javax.swing.JTextField();
        TxtFrom = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        autoFillFee = new javax.swing.JTextField();
        AutoFillBatch = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegIdSearch = new javax.swing.JTextField();
        AutoFillName = new javax.swing.JTextField();
        AutoFillStudentId = new javax.swing.JTextField();
        AutoFillCourseName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        batchtxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jPanel3.setBackground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BATCH TRANSFERRING");

        HOME_TIME1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME1.setForeground(new java.awt.Color(255, 255, 255));

        HOME_TIME.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_TIME1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HOME_TIME1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_TIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtTo.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel4.add(TxtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 98, 497, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setText("TO");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 106, -1, -1));

        TxtBtid.setEditable(false);
        TxtBtid.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel4.add(TxtBtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 6, 497, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("BTID");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setText("From");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Fee");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 143, -1, -1));

        TxtBtFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBtFeeActionPerformed(evt);
            }
        });
        jPanel4.add(TxtBtFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 138, 497, -1));

        TxtFrom.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel4.add(TxtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 52, 497, -1));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 149, 110, 45));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton4.setText("transfer Batch");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 149, -1, 45));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel16.setText("jLabel14");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 200));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel27.setText("jLabel14");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 200));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel17.setText("jLabel14");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 170, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        autoFillFee.setEditable(false);
        autoFillFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFillFeeActionPerformed(evt);
            }
        });
        jPanel2.add(autoFillFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 207, 496, -1));

        AutoFillBatch.setEditable(false);
        AutoFillBatch.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel2.add(AutoFillBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 253, 496, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel20.setText("Batch");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 257, -1, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel21.setText("Fee");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 211, -1, -1));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setText("Course Name");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 165, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Student ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 119, -1, -1));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel23.setText("Student Name");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 73, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Reg Id");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, -1));

        RegIdSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegIdSearchMouseClicked(evt);
            }
        });
        RegIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegIdSearchActionPerformed(evt);
            }
        });
        jPanel2.add(RegIdSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 16, 396, -1));

        AutoFillName.setEditable(false);
        AutoFillName.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel2.add(AutoFillName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 69, 496, -1));

        AutoFillStudentId.setEditable(false);
        AutoFillStudentId.setMinimumSize(new java.awt.Dimension(6, 30));
        AutoFillStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoFillStudentIdActionPerformed(evt);
            }
        });
        jPanel2.add(AutoFillStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 115, 496, -1));

        AutoFillCourseName.setEditable(false);
        AutoFillCourseName.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel2.add(AutoFillCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 161, 496, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 6, -1, 45));

        batchtxt.setEditable(false);
        jPanel2.add(batchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 250, 132, -1));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel24.setText("Frist Batches");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 254, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel15.setText("jLabel14");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 280));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel26.setText("jLabel14");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 280));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 170, 280));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BTID", "Registration Id", "From", "To", "Fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBtFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBtFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBtFeeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void autoFillFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFillFeeActionPerformed
        // TODO add your handling code here:
        //  batchTransferController.

    }//GEN-LAST:event_autoFillFeeActionPerformed

    private void RegIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegIdSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegIdSearchActionPerformed

    private void AutoFillStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoFillStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoFillStudentIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        try {
            BatchTransferDTO SearchAllAndShort = batchTransferController.SearchAllAndShort(RegIdSearch.getText());
            if (SearchAllAndShort != null) {
                batchtxt.setText(SearchAllAndShort.getToBatch());
                TxtFrom.setText(SearchAllAndShort.getToBatch());
            }
        } catch (Exception ex) {
            Logger.getLogger(BatchTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            PaymentDTO p = paymentController.SearchAllAndShort(RegIdSearch.getText());
            if (p != null) {

                JOptionPane.showMessageDialog(rootPane, "This Student's PaymentDetails :-" + "      Id is:-" + p.getPid() + "         Arrears is:- " + p.getArrears() + "          Next Payment Date is:- " + p.getNextPaymentDate());
            }

            try {
                RegistrationDTO SearchAllAndShort = registrationController.SearchAllAndShort(RegIdSearch.getText());
                registrationDTO=SearchAllAndShort;
                if (SearchAllAndShort != null) {
                    System.out.println(SearchAllAndShort.getBatchid() + "");
                    BatchDTO SearchAllAndShort2 = batchController.Search(SearchAllAndShort.getBatchid());
                    System.out.println(SearchAllAndShort2.toString());

                    if (SearchAllAndShort != null) {
                        CourseDTO SearchAllAndShort3 = courseController.Search(SearchAllAndShort2.getCourseId());

                        if (SearchAllAndShort3 != null) {
                            StudentDTO SearchAllAndShort4 = studentController.Search(SearchAllAndShort.getStudentid());

                            if (SearchAllAndShort4 != null) {
                                AutoFillName.setText(SearchAllAndShort4.getFullname());
                                AutoFillStudentId.setText(SearchAllAndShort4.getSid());
                                AutoFillCourseName.setText(SearchAllAndShort3.getCoursename());
                                autoFillFee.setText(SearchAllAndShort2.getFee());
                                AutoFillBatch.setText(SearchAllAndShort2.getBatch());
                                TxtFrom.setText(SearchAllAndShort2.getBatch());
                                String str = RegIdSearch.getText();
                                String strNew = str.replace("R", "T");
//                                TxtBtid.setText(strNew);

                            } else {
                                System.out.println("sort 4 null");
                            }
                        } else {
                            System.out.println("sort 3 null");
                        }
                    }
                } else {
                    System.out.println("sort 1 null");
                }

            } catch (Exception ex) {
                Logger.getLogger(BatchTransfer.class.getName()).log(Level.SEVERE, null, ex);
            }
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(BatchTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BatchTransferDTO batchTransfer = new BatchTransferDTO(TxtBtid.getText(), RegIdSearch.getText(), TxtFrom.getText(), TxtTo.getText(), TxtBtFee.getText());

        try {
            boolean add = batchTransferController.add(batchTransfer);
            if (add) {
                System.out.println(" Add Ok");
                JOptionPane.showMessageDialog(rootPane, "Batch Transferring Is Success");
                ViewAll();
                regupdate();
                collectingBills();
                jasperReport();
                ClearTXt();
            } else {
               // registrationDTO=null;
                System.out.println(" Not Add");
                JOptionPane.showMessageDialog(rootPane, "Batch Transferring Is Success");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCourse.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton4ActionPerformed
private void regupdate(){
    String name=TxtTo.getText();
        try {
      //  BatchDTO SearchAllAndShort = batchController.SearchAllandsort2(name);
        registrationDTO.setBatchid(TxtTo.getText());
        
          //  System.out.println("bid "+SearchAllAndShort.getBid());
        
        boolean Update = registrationController.Update(registrationDTO);
            if (Update) {
                System.out.println("ok");
            }else{
                System.out.println("false");
            }
        } catch (Exception ex) {
            Logger.getLogger(BatchTransfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    
} 
    private void RegIdSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegIdSearchMouseClicked
        ClearTXt();        // TODO add your handling code here:
    }//GEN-LAST:event_RegIdSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutoFillBatch;
    private javax.swing.JTextField AutoFillCourseName;
    private javax.swing.JTextField AutoFillName;
    private javax.swing.JTextField AutoFillStudentId;
    private javax.swing.JLabel HOME_TIME;
    private javax.swing.JLabel HOME_TIME1;
    private javax.swing.JTextField RegIdSearch;
    private javax.swing.JTextField TxtBtFee;
    private javax.swing.JTextField TxtBtid;
    private javax.swing.JTextField TxtFrom;
    private javax.swing.JTextField TxtTo;
    private javax.swing.JTextField autoFillFee;
    private javax.swing.JTextField batchtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String currentdate = new SimpleDateFormat("hh:mm:aa").format(date);
                    HOME_TIME.setText(currentdate);

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        HOME_TIME1.setText(s.format(d));

    }

    private void ViewAll() {
        try {
            ArrayList<BatchTransferDTO> SearchAll = batchTransferController.SearchAll();
            DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
            defaultTableModel.setRowCount(0);

            for (BatchTransferDTO i1 : SearchAll) {
                if (i1.getToBatch().equals("No Transfer")) {

                } else {
                    Object[] rodate = {i1.getbTID(), i1.getRegistrationId(), i1.getFromBatch(), i1.getToBatch(), i1.getBtFee()};
                    defaultTableModel.addRow(rodate);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Idgent1() {
        tableName = "batchtransferring";
        columName = "BTID";
        prefix = "T";
        TxtBtid.setText(IDGenarator.getNextIdGenaretor(tableName, columName, prefix));

    }

    private void jasperReport() {

        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/lk//edu//ijse//Reports/StudentDetailsWitBTReportGetUI.jasper"));

            HashMap<String, Object> parHashMap = new HashMap<>();
            parHashMap.put("SID", RegIdSearch.getText());
            parHashMap.put("NwithInit", AutoFillName.getText());
            parHashMap.put("FullName", AutoFillStudentId.getText());
            parHashMap.put("Nic", AutoFillCourseName.getText());
            parHashMap.put("Address", autoFillFee.getText());
            parHashMap.put("Telephone", AutoFillBatch.getText());

            parHashMap.put("BTID", TxtBtid.getText());
            parHashMap.put("From", TxtFrom.getText());
            parHashMap.put("To", TxtTo.getText());
            parHashMap.put("Fee", TxtBtFee.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, new JREmptyDataSource());
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            java.awt.Container container = jasperViewer.getContentPane();

            JDialog jDialog = new JDialog();
            jDialog.setContentPane(container);
            jDialog.setSize(jasperViewer.getSize());
            jDialog.setLocationRelativeTo(null);
            jDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ClearTXt() {
        RegIdSearch.setText("");
        AutoFillName.setText("");
        AutoFillStudentId.setText("");
        AutoFillCourseName.setText("");
        autoFillFee.setText("");
        AutoFillBatch.setText("");
        TxtBtFee.setText("");
        TxtBtid.setText("");
        TxtFrom.setText("");
        TxtTo.setText("");
        Idgent1();
    }

    private void Idgent() {
        tableName = "batchtransferring";
        columName = "BTID";
        prefix = "T";
        TxtBtid.setText(IDGenarator.getNextIdGenaretor(tableName, columName, prefix));

    }

    private void collectingBills() {
        DailycollectionDTO dailycollectionDTO = new DailycollectionDTO(0,"Batch Transfer",AutoFillBatch.getText(), HOME_TIME1.getText(), TxtBtFee.getText());

        try {
            boolean add = dailyCollectionController.add(dailycollectionDTO);
            if (add) {
                System.out.println(" Add Ok");
//                JOptionPane.showMessageDialog(rootPane, "afsdsdfasdfasf");
            } else {
                System.out.println(" Not Add");
//                JOptionPane.showMessageDialog(rootPane, "aefdadsf");
            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrationWithPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
