/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import lk.edu.ijse.controller.ControllerFactory;
import lk.edu.ijse.controller.custom.DailyCollectionController;
import lk.edu.ijse.db.DBConnection;
import lk.edu.ijse.dto.DailycollectionDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author epc
 */
public class Incomes extends javax.swing.JFrame {

    private double paymentttttt;
    private int stateeeee;
    private int dayss;
    private int Scount = 0;
    private DailyCollectionController dailyCollectionController;
    Connection connection;

    /**
     * Creates new form Incomes
     */
    public Incomes() {
        connection = DBConnection.getDBConnection().getConnection();
        initComponents();
        setTime();
        setDate();
//        setSize(1362, 909);
        dailyCollectionController = (DailyCollectionController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.DAILYCOLLECTION);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HOME_TIME1 = new javax.swing.JLabel();
        HOME_TIME = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        PaymentViewLbl = new javax.swing.JLabel();
        LastMonthBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Cmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Cmb1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cmb2 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Cmb3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Summeries");

        HOME_TIME1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME1.setForeground(new java.awt.Color(255, 255, 255));

        HOME_TIME.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_TIME1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216)
                .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HOME_TIME1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        PaymentViewLbl.setBackground(new java.awt.Color(0, 0, 0));
        PaymentViewLbl.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        PaymentViewLbl.setForeground(new java.awt.Color(255, 255, 255));
        PaymentViewLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaymentViewLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentViewLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentViewLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaymentViewLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 90));

        LastMonthBtn.setBackground(new java.awt.Color(153, 204, 255));
        LastMonthBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        LastMonthBtn.setText("Last Month");
        LastMonthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastMonthBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LastMonthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 114, -1, 45));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setText("Last 3 Month");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 114, -1, 45));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("last year");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 114, 122, 45));

        jTextField2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 213, 200, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 1380, 10));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("check date income (yyyy-MM-dd)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 212, 209, 33));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 205, 132, 45));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel12.setText("Full Income Summery");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 297, -1, 38));

        Cmb.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration", "Payment", "Batch Transfer" }));
        Cmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbItemStateChanged(evt);
            }
        });
        Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbActionPerformed(evt);
            }
        });
        jPanel2.add(Cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 305, 198, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Catagory To Payment Type");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 310, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 353, 1386, 10));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("check Batch income");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 388, 143, 33));

        jTextField3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 389, 200, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("batch Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 381, -1, 45));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel9.setText("Btach full Income");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 382, 303, 38));

        Cmb1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration", "Payment", "Batch Transfer" }));
        Cmb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb1ItemStateChanged(evt);
            }
        });
        jPanel2.add(Cmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 475, 182, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Payment Type");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 480, -1, -1));

        jTextField1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 474, 200, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("date  (yyyy-MM-dd)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 473, 178, 33));

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1199, 472, 135, 45));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel11.setText("Student Count To Due Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 563, -1, 38));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("date  (yyyy-MM-dd)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 566, 178, 33));

        jTextField4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 567, 200, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Student Type");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 573, 103, -1));

        Cmb2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration", "Payment", "Batch Transfer" }));
        Cmb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb2ItemStateChanged(evt);
            }
        });
        jPanel2.add(Cmb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 566, 182, -1));

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 563, 135, 45));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 626, 1380, 10));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setText("Batch");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 664, 178, 33));

        jTextField5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 665, 200, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel15.setText("Student Type");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 671, 103, -1));

        Cmb3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration", "Payment", "Batch Transfer" }));
        Cmb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb3ItemStateChanged(evt);
            }
        });
        jPanel2.add(Cmb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 666, 182, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel14.setText("Student Count To Batch");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 654, 270, 38));

        jButton8.setBackground(new java.awt.Color(153, 204, 255));
        jButton8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 657, 135, 45));

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 748, 135, 45));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 269, 1380, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 444, 1380, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 1380, 10));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel16.setText("Income daily");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 206, 303, 38));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel17.setText("Monthly Income Summery");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, -1, 38));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel18.setText("Daily Income With Payment Types");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 472, -1, 38));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1380, 10));

        jButton9.setBackground(new java.awt.Color(153, 204, 255));
        jButton9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton9.setText("Search this day all registration details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 205, 340, 45));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel19.setText("jLabel14");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 610, 610));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel26.setText("jLabel14");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 610, 610));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel20.setText("jLabel14");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 180, 610));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel21.setText("jLabel14");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 700, 610, 120));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel27.setText("jLabel14");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 610, 120));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel22.setText("jLabel14");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 700, 200, 120));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel23.setText("jLabel14");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 620, 250));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel28.setText("jLabel14");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 250));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel24.setText("jLabel14");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 180, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastMonthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastMonthBtnActionPerformed
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                String b = HOME_TIME1.getText();
                dayss = DateDeference(a, b);
                int c = dayss;

                System.out.println(c);
                if (c < 30) {

                    System.out.println("" + registrationDTO.getPayyy());
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);
//                    paymentttttt=0;

                } else {
                }

//            BatchTransferDTO SearchAllAndShort = batchTransferController.SearchAllAndShort(registrationDTO.getRid());
//            if (SearchAllAndShort==null) {
//                        System.out.println("fddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
//Object[] rodate = {rid, bid, SearchAll.getSid(), SearchAll.getNameWithInitial(), SearchAll.getFullname(), SearchAll.getTel(), SearchAll.getNic(), SearchAll.getAddress(), SearchAll.getSchool(), SearchAll.getGender(), SearchAll.getEducationState(), SearchAll.getDob(), "No Batch Transfer"};
//    System.out.println("2" + SearchAll.getTel());
//defaultTableModel.addRow(rodate);
//            }else{
//                Object[] rodate = {rid, bid, SearchAll.getSid(), SearchAll.getNameWithInitial(), SearchAll.getFullname(), SearchAll.getTel(), SearchAll.getNic(), SearchAll.getAddress(), SearchAll.getSchool(), SearchAll.getGender(), SearchAll.getEducationState(), SearchAll.getDob(), SearchAllAndShort.getbTID()};
                //    System.out.println("2" + SearchAll.getTel());
//                defaultTableModel.addRow(rodate);
//            }
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {

            paymentttttt = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LastMonthBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                String b = HOME_TIME1.getText();
                dayss = DateDeference(a, b);
                int c = dayss;

                System.out.println(c);
                if (c < 90) {

                    System.out.println("" + registrationDTO.getPayyy());
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);

                } else {
                }
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {
            paymentttttt = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbItemStateChanged
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {

                String f = registrationDTO.getStatee();
//                System.out.println("db"+f);
                String g = (String) Cmb.getSelectedItem();
//                System.out.println("cmb"+g);
                if (g.equals(f)) {
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());

                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);
                }
//                } else if (g.equals(f) && f.equals("Registration")) {
//
//                    stateeeee += Integer.parseInt(registrationDTO.getPayyy());
//                    String d = "Rs. " + paymentttttt;
//                    PaymentViewLbl.setText(d);
//                    paymentttttt = 0;
//                } else {
//                    stateeeee += Integer.parseInt(registrationDTO.getPayyy());
//                    String d = "Rs. " + paymentttttt;
//                    PaymentViewLbl.setText(d);
//                    paymentttttt = 0;
//                }
            }// TODO add your handling code here:

            paymentttttt = 0;
        } catch (Exception ex) {
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_CmbItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                String b = HOME_TIME1.getText();
                dayss = DateDeference(a, b);
                int c = dayss;

                System.out.println(c);
                if (c < 364) {

                    System.out.println("" + registrationDTO.getPayyy());
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);

                } else {
                }
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {
            paymentttttt = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getBatchhh();
                System.out.println("db" + a);
                String b = jTextField3.getText();
                System.out.println("tf" + b);

                if (b.equals(a)) {
                    System.out.println("hbhbbhbhbh");
                    System.out.println("" + registrationDTO.getPayyy());
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);

                } else {
//                    System.out.println("no");
                }
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {
            paymentttttt = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                System.out.println("db" + a);
                String b = jTextField2.getText();
                System.out.println("tf" + b);

                if (b.equals(a)) {
                    System.out.println("hbhbbhbhbh");
                    System.out.println("" + registrationDTO.getPayyy());
                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                    String d = "Rs. " + paymentttttt + "0";
                    PaymentViewLbl.setText(d);

                } else {
//                    System.out.println("no");
                }
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CheckPaymentStates checkPaymentStates = new CheckPaymentStates();
        checkPaymentStates.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Cmb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String e = "Rs.0.00";
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                String b = jTextField1.getText();
                String c = (String) Cmb1.getSelectedItem();
                String d = registrationDTO.getStatee();

                if (b.equals(a)) {

                    if (c.equals(d)) {
//                        System.out.println("hbhbbhbhbh");
                        System.out.println("" + registrationDTO.getPayyy());
                        paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
                        e = "Rs. " + paymentttttt + "0";

                    }
                } else {
//                    e="0";
//                    System.out.println("no");
                }
                PaymentViewLbl.setText(e);
            }// TODO add your handling code here:
            paymentttttt = 0;
        } catch (Exception ex) {
            paymentttttt = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }
//                  ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
//            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
//
//                String f = registrationDTO.getStatee();
////                System.out.println("db"+f);
//                String g = (String) Cmb.getSelectedItem();
////                System.out.println("cmb"+g);
//                if (g.equals(f)) {
//                    paymentttttt += Integer.parseInt(registrationDTO.getPayyy());
//                  
//                    String d = "Rs. " + paymentttttt;
//                    PaymentViewLbl.setText(d);
//                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbActionPerformed

    private void Cmb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb2ItemStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String e = "0 Student/(s)";
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getDateee();
                String b = jTextField4.getText();
                String c = (String) Cmb2.getSelectedItem();
                String d = registrationDTO.getStatee();

                if (b.equals(a)) {
                    //System.out.println(a+"  jj");
                    if (c.equals(d)) {

                        Scount += 1;
                        e = Scount + "  Student/(s)";

                    }
                } else {
                    // e="0";
//                    System.out.println("no");
                }
                PaymentViewLbl.setText(e);
            }// TODO add your handling code here:
            Scount = 0;
        } catch (Exception ex) {
            Scount = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            String e = "0 Student/(s)";
            ArrayList<DailycollectionDTO> SearchAllAndSort11 = dailyCollectionController.SearchAll();
            for (DailycollectionDTO registrationDTO : SearchAllAndSort11) {
                //    System.out.println("2" + SearchAll.getTel());
                String a = registrationDTO.getBatchhh();
                String b = jTextField5.getText();
                String c = (String) Cmb3.getSelectedItem();
                String d = registrationDTO.getStatee();

                if (b.equals(a)) {
                    if (c.equals(d)) {

                        Scount += 1;
                        e = Scount + "  Student/(s)";
                    }
                } else {
//                    System.out.println("no");
                }

                PaymentViewLbl.setText(e);
            }// TODO add your handling code here:
            Scount = 0;
        } catch (Exception ex) {

            Scount = 0;
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling c        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Cmb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb3ItemStateChanged

    private void PaymentViewLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentViewLblMouseClicked
        PaymentViewLbl.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentViewLblMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        px();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incomes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb;
    private javax.swing.JComboBox<String> Cmb1;
    private javax.swing.JComboBox<String> Cmb2;
    private javax.swing.JComboBox<String> Cmb3;
    private javax.swing.JLabel HOME_TIME;
    private javax.swing.JLabel HOME_TIME1;
    private javax.swing.JButton LastMonthBtn;
    private javax.swing.JLabel PaymentViewLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String currentdate = new SimpleDateFormat("hh:mm:aa").format(date);
                    HOME_TIME.setText(currentdate);

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        HOME_TIME1.setText(s.format(d));

    }

    public int DateDeference(String date, String curentDate) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);

            Date firstDate = sdf.parse(date);
            Date secondDate = sdf.parse(curentDate);

            List<Date> dates = new ArrayList<Date>();
            dates.add(firstDate);
            dates.add(secondDate);

            int diffInMillies = (int) Math.abs(secondDate.getTime() - firstDate.getTime());
            int diff = (int) TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
            if (!sdf.format(Collections.max(dates)).equals(date)) {
                return 0;
            }
            return diff;
        } catch (ParseException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }

    }

    private void px() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/IJSEPayments", "root", "ijse");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StartUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/lk//edu//ijse//Reports/regSearchWithDate.jasper"));

            HashMap<String, Object> parHashMap = new HashMap<>();
            parHashMap.put("RegDate", jTextField2.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, connection);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            java.awt.Container container = jasperViewer.getContentPane();

            JDialog jDialog = new JDialog();
            jDialog.setContentPane(container);
            jDialog.setSize(jasperViewer.getSize());
            jDialog.setLocationRelativeTo(null);
            jDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Incomes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, conn);
//            System.out.println(jasperPrint);
//            JasperReportViewer jasperReportViewer = new JasperReportViewer(jasperPrint);
//            jasperReportViewer.setVisible(true);
//            
//            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, new HashMap<>(), conn);
//            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
//            java.awt.Container container = jasperViewer.getContentPane();
//
//            JDialog jDialog = new JDialog();
//
//            jDialog.setContentPane(container);
//            jDialog.setSize(jasperViewer.getSize());
//            jDialog.setLocationRelativeTo(null);
//            jDialog.setVisible(true);
//            
}

