/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import lk.edu.ijse.controller.ControllerFactory;
import lk.edu.ijse.controller.custom.BatchController;
import lk.edu.ijse.controller.custom.CourseController;
import lk.edu.ijse.controller.custom.DailyCollectionController;
import lk.edu.ijse.controller.custom.PaymentController;
import lk.edu.ijse.controller.custom.RegistrationController;
import lk.edu.ijse.controller.custom.StudentController;
import lk.edu.ijse.dto.BatchDTO;
import lk.edu.ijse.dto.CourseDTO;
import lk.edu.ijse.dto.DailycollectionDTO;
import lk.edu.ijse.dto.PaymentDTO;
import lk.edu.ijse.dto.RegistrationDTO;
import lk.edu.ijse.dto.StudentDTO;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author epc
 */
public class Payments extends javax.swing.JFrame {

    private RegistrationController registrationController;
    private CourseController courseController;
    private BatchController batchController;
    private StudentController studentController;
    private DailyCollectionController dailyCollectionController;
    private PaymentController paymentController;
    private int calPaymentWithTax;
    private int x;
    private int Tax;
    private int latedates;
    private String NXTPaymentDate;

    private String Dis;
    private String NICC;
    private String StartDAteeee;
    private String Taxxx;
    private String Lateeeeee;

    /**
     * Creates new form Payments
     */
    public Payments() {
        initComponents();
        setLocationRelativeTo(null);
        registrationController = (RegistrationController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.REGISTRATION);
        dailyCollectionController = (DailyCollectionController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.DAILYCOLLECTION);
        studentController = (StudentController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.STUDENT);
        batchController = (BatchController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.BATCH);
        courseController = (CourseController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.COURSE);
        paymentController = (PaymentController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.PAYMENT);

        setTime();
        setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HOME_TIME1 = new javax.swing.JLabel();
        HOME_TIME = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        autoFillFee = new javax.swing.JTextField();
        AutoFillBatch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegIdSearch = new javax.swing.JTextField();
        AutoFillName = new javax.swing.JTextField();
        AutoFillStudentId = new javax.swing.JTextField();
        AutoFillCourseName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LatePaymentTxt = new javax.swing.JTextField();
        taxWithPayment1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        taxWithPayment2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jLabel14.setText("Fee");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jPanel3.setBackground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENT");

        HOME_TIME1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME1.setForeground(new java.awt.Color(255, 255, 255));

        HOME_TIME.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_TIME1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(HOME_TIME1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HOME_TIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButton4.setText("1st Payment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1236, 45));

        autoFillFee.setEditable(false);
        autoFillFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFillFeeActionPerformed(evt);
            }
        });
        jPanel2.add(autoFillFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 292, 479, -1));

        AutoFillBatch.setEditable(false);
        AutoFillBatch.setMinimumSize(new java.awt.Dimension(6, 30));
        AutoFillBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoFillBatchActionPerformed(evt);
            }
        });
        jPanel2.add(AutoFillBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 346, 479, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setText("Batch");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Fee");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 296, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setText("Course Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 241, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Student ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 187, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("Student Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 129, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Reg Id");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 73, -1, -1));

        RegIdSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegIdSearchMouseClicked(evt);
            }
        });
        RegIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegIdSearchActionPerformed(evt);
            }
        });
        jPanel2.add(RegIdSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 69, 479, -1));

        AutoFillName.setEditable(false);
        AutoFillName.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel2.add(AutoFillName, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 125, 479, -1));

        AutoFillStudentId.setEditable(false);
        AutoFillStudentId.setMinimumSize(new java.awt.Dimension(6, 30));
        AutoFillStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoFillStudentIdActionPerformed(evt);
            }
        });
        jPanel2.add(AutoFillStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 183, 479, -1));

        AutoFillCourseName.setEditable(false);
        AutoFillCourseName.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel2.add(AutoFillCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 237, 480, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel19.setText("jLabel14");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel26.setText("jLabel14");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 380));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel20.setText("jLabel14");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 50, 380));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Payment Id");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 22, -1, -1));

        jTextField2.setEditable(false);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 18, 478, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setText("Arrears Payment");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 78, -1, -1));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 74, 478, -1));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 226, 114, 45));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 226, 120, 45));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel15.setText("Full Payment");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 170, -1, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 166, 478, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setText("Late Payment");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 124, -1, -1));

        LatePaymentTxt.setEditable(false);
        jPanel4.add(LatePaymentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 120, 478, -1));

        taxWithPayment1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taxWithPayment1KeyReleased(evt);
            }
        });
        jPanel4.add(taxWithPayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 200, 478, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setText("Payment");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 204, -1, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel18.setText("Balance");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 250, -1, -1));

        taxWithPayment2.setEditable(false);
        jPanel4.add(taxWithPayment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 246, 478, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel21.setText("jLabel14");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 290));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel27.setText("jLabel14");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 290));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel22.setText("jLabel14");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 50, 290));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        RegistrationWithPayment registrationWithPayment = new RegistrationWithPayment();
        registrationWithPayment.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void autoFillFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFillFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoFillFeeActionPerformed

    private void RegIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegIdSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegIdSearchActionPerformed

    private void AutoFillStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoFillStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoFillStudentIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            RegistrationDTO SearchAllAndShort = registrationController.SearchAllAndShort(RegIdSearch.getText());
            if (SearchAllAndShort != null) {
                System.out.println(SearchAllAndShort.getBatchid() + "");
                BatchDTO SearchAllAndShort2 = batchController.Search(SearchAllAndShort.getBatchid());
                System.out.println(SearchAllAndShort2.toString());

                if (SearchAllAndShort != null) {
                    CourseDTO SearchAllAndShort3 = courseController.Search(SearchAllAndShort2.getCourseId());

                    if (SearchAllAndShort3 != null) {
                        StudentDTO SearchAllAndShort4 = studentController.Search(SearchAllAndShort.getStudentid());

                        if (SearchAllAndShort4 != null) {
                            AutoFillName.setText(SearchAllAndShort4.getFullname());
                            NICC = SearchAllAndShort4.getNic();
//                                iid = SearchAllAndShort1.getBid();
                            AutoFillStudentId.setText(SearchAllAndShort4.getSid());
                            AutoFillCourseName.setText(SearchAllAndShort3.getCoursename());
                            autoFillFee.setText(SearchAllAndShort2.getFee());
                            AutoFillBatch.setText(SearchAllAndShort2.getBatch());
                            StartDAteeee = SearchAllAndShort2.getStartDate();

                            Taxxx = SearchAllAndShort3.getTaxRate();

                            PaymentDTO SearchAllAnsShort5 = paymentController.SearchAllAndShort(RegIdSearch.getText());
                            jTextField2.setText(SearchAllAnsShort5.getPid());
                            jTextField11.setText(SearchAllAnsShort5.getArrears());
                            String abc = SearchAllAnsShort5.getArrears();
                            setDate1();
                            String nowDate = SearchAllAnsShort5.getNextPaymentDate();
                            System.out.println("" + nowDate);
                            System.out.println("" + NXTPaymentDate);
                            Tax = Integer.parseInt(SearchAllAndShort3.getTaxRate()) + 100;
                            LatePaymentTxt.setText("0");
                            Lateeeeee="0";
                            if (abc.equals("No Arrears")) {
                                jTextField12.setText("No Arrears Payments");
                            } else {

                                latedates = DateDeference(NXTPaymentDate, nowDate);
                                
                                LatePaymentTxt.setText("" + latedates);
                                Lateeeeee=LatePaymentTxt.getText();
                                calArrears();
                                
                            }

//                    } else {
                        } else {
                            System.out.println("sort 4 null");
                        }
                    } else {
                        System.out.println("sort 3 null");
                    }
                }
            } else {
                System.out.println("sort 1 null");
            }

        } catch (Exception ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            PaymentDTO payment = new PaymentDTO(jTextField2.getText(), RegIdSearch.getText(), "Full Payment", "No Arrears", "Payment Is End");
            System.out.println(payment.getPid());
            boolean Update = paymentController.Update(payment);
            if (Update) {
                JOptionPane.showMessageDialog(null, "Payment Is Succes");
                collectingBills();
                jasperReport2();
            } else {
                JOptionPane.showMessageDialog(null, "Payment Is Not Suscces");
            }
        } catch (Exception ex) {
            Logger.getLogger(UpdateCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AutoFillBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoFillBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoFillBatchActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void RegIdSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegIdSearchMouseClicked
        ClearTXt();        // TODO add your handling code here:
    }//GEN-LAST:event_RegIdSearchMouseClicked

    private void taxWithPayment1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxWithPayment1KeyReleased
        balancecal();        // TODO add your handling code here:
    }//GEN-LAST:event_taxWithPayment1KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        balancecal();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutoFillBatch;
    private javax.swing.JTextField AutoFillCourseName;
    private javax.swing.JTextField AutoFillName;
    private javax.swing.JTextField AutoFillStudentId;
    private javax.swing.JLabel HOME_TIME;
    private javax.swing.JLabel HOME_TIME1;
    private javax.swing.JTextField LatePaymentTxt;
    private javax.swing.JTextField RegIdSearch;
    private javax.swing.JTextField autoFillFee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField taxWithPayment1;
    private javax.swing.JTextField taxWithPayment2;
    // End of variables declaration//GEN-END:variables

    private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String currentdate = new SimpleDateFormat("hh:mm:aa").format(date);
                    HOME_TIME.setText(currentdate);

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        HOME_TIME1.setText(s.format(d));

    }

    private void setDate1() {
        Date b = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM/dd/yy");
        NXTPaymentDate = s.format(b);

    }

    private void calArrears() {
        if (latedates > 0) {
            x = (Integer.parseInt(autoFillFee.getText()) / 2);
            calPaymentWithTax = x * Tax / 100;
            int g = x * latedates;
            int j = g / 100;
            int h = calPaymentWithTax + j;
            jTextField12.setText("" + h);
            calPaymentWithTax = 0;
            g = 0;
        } else {
            x = (Integer.parseInt(autoFillFee.getText()) / 2);
            calPaymentWithTax = x * Tax / 100;
            jTextField12.setText("" + calPaymentWithTax);
            calPaymentWithTax = 0;
        }
    }

    private void jasperReport() {

        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/lk//edu//ijse//Reports/PaymentWithStudentGetUI.jasper"));

            HashMap<String, Object> parHashMap = new HashMap<>();
            parHashMap.put("SID", RegIdSearch.getText());
            parHashMap.put("NwithInit", AutoFillName.getText());
            parHashMap.put("FullName", AutoFillStudentId.getText());
            parHashMap.put("Nic", AutoFillCourseName.getText());
            parHashMap.put("Address", autoFillFee.getText());
            parHashMap.put("Telephone", AutoFillBatch.getText());

            parHashMap.put("paymentstate", "Payment End");
            parHashMap.put("Arrears", jTextField11.getText());
            parHashMap.put("pid", jTextField2.getText());
            parHashMap.put("NextPaymentDate", "Payment End");
            parHashMap.put("FuulPay", jTextField12.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, new JREmptyDataSource());
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            java.awt.Container container = jasperViewer.getContentPane();

            JDialog jDialog = new JDialog();
            jDialog.setContentPane(container);
            jDialog.setSize(jasperViewer.getSize());
            jDialog.setLocationRelativeTo(null);
            jDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ClearTXt() {
        RegIdSearch.setText("");
        AutoFillName.setText("");
        AutoFillStudentId.setText("");
        AutoFillCourseName.setText("");
        autoFillFee.setText("");
        AutoFillBatch.setText("");
        jTextField2.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
    }

    public int DateDeference(String date, String curentDate) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH);

            Date firstDate = sdf.parse(date);
            Date secondDate = sdf.parse(curentDate);

            List<Date> dates = new ArrayList<Date>();
            dates.add(firstDate);
            dates.add(secondDate);

            int diffInMillies = (int) Math.abs(secondDate.getTime() - firstDate.getTime());
            int diff = (int) TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
            if (!sdf.format(Collections.max(dates)).equals(date)) {
                return 0;
            }
            return diff;
        } catch (ParseException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }

    }

    private void balancecal() {
        int r = Integer.parseInt(taxWithPayment1.getText());
        int e = Integer.parseInt(jTextField12.getText());
        int t = r - e;
        taxWithPayment2.setText("" + t);
    }

    private void jasperReport2() {

        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/lk//edu//ijse//Reports/Invoicee.jasper"));
//            String h = (String) CmbPaymentStete.getSelectedItem();
            HashMap<String, Object> parHashMap = new HashMap<>();
            parHashMap.put("ReceptDate", HOME_TIME1.getText());
            parHashMap.put("NIC", NICC);
            parHashMap.put("SName", AutoFillName.getText());
            parHashMap.put("Batch", AutoFillBatch.getText());
            parHashMap.put("NxtPayment", StartDAteeee);
            parHashMap.put("CourseName", AutoFillCourseName.getText());
            parHashMap.put("PaymentState", "Last Payment");
            parHashMap.put("NxtPaymentDatee", "payment End");
            parHashMap.put("Latee",Lateeeeee);

            parHashMap.put("Fee", jTextField11.getText());

            parHashMap.put("TaxTxt", Taxxx);
            parHashMap.put("Dis", "No");

            parHashMap.put("FullFee", jTextField12.getText());
            parHashMap.put("Payment", taxWithPayment1.getText());
            parHashMap.put("balance", taxWithPayment2.getText());
            parHashMap.put("Arrears", "No Arrears");

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, new JREmptyDataSource());
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            java.awt.Container container = jasperViewer.getContentPane();

            JDialog jDialog = new JDialog();
            jDialog.setContentPane(container);
            jDialog.setSize(jasperViewer.getSize());
            jDialog.setLocationRelativeTo(null);
            jDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void collectingBills(){
    DailycollectionDTO dailycollectionDTO = new DailycollectionDTO(0,"Payment",AutoFillBatch.getText(), HOME_TIME1.getText(), jTextField12.getText());

        try {
            boolean add = dailyCollectionController.add(dailycollectionDTO);
            if (add) {
                System.out.println(" Add Ok");
//                JOptionPane.showMessageDialog(rootPane, "afsdsdfasdfasf");
            } else {
                System.out.println(" Not Add");
//                JOptionPane.showMessageDialog(rootPane, "aefdadsf");
            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrationWithPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
}

}
