/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.view;

import lk.edu.ijse.utill.IDGenarator;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import lk.edu.ijse.controller.ControllerFactory;
import lk.edu.ijse.controller.custom.BatchController;
import lk.edu.ijse.controller.custom.BatchTransferController;
import lk.edu.ijse.controller.custom.CourseController;
import lk.edu.ijse.controller.custom.DailyCollectionController;
import lk.edu.ijse.controller.custom.RegistrationController;
import lk.edu.ijse.dto.BatchDTO;
import lk.edu.ijse.dto.BatchTransferDTO;
import lk.edu.ijse.dto.CourseDTO;
import lk.edu.ijse.dto.DailycollectionDTO;
import lk.edu.ijse.dto.RegistrationDTO;
import lk.edu.ijse.dto.StudentDTO;
import lk.edu.ijse.utill.Validator;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author epc
 */
public class Registration extends javax.swing.JFrame {

    public CourseController courseController;
    private BatchController batchController;
    private BatchTransferController batchTransferController;
    private RegistrationController registrationController;
    private DailyCollectionController dailyCollectionController;
    private String iid;
    private String prefix;
    private String tableName;
    private String columName;
    private String prefix1;
    private String tableName1;
    private String columName1;

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();

        setLocationRelativeTo(null);
        registrationController = (RegistrationController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.REGISTRATION);
        dailyCollectionController = (DailyCollectionController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.DAILYCOLLECTION);
        batchTransferController = (BatchTransferController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.BATCHTRANSFER);
        batchController = (BatchController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.BATCH);
        courseController = (CourseController) ControllerFactory.getIntense().getServices(ControllerFactory.getServicesType.COURSE);

//        loadCombo();
        Idgent1();
        Idgent();

        Radio();
        loadCombo2();
        setTime();
        setDate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HOME_TIME1 = new javax.swing.JLabel();
        HOME_TIME = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtStudentId = new javax.swing.JTextField();
        TxtStudentAddress = new javax.swing.JTextField();
        TxtStudentNameWithInitial = new javax.swing.JTextField();
        TxtStudentNic = new javax.swing.JTextField();
        TxtStudentFullName = new javax.swing.JTextField();
        DateChooserStudentDOB = new datechooser.beans.DateChooserCombo();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TxtStudentSchool = new javax.swing.JTextField();
        TxtStudentTel = new javax.swing.JTextField();
        RadioMale = new javax.swing.JRadioButton();
        RadioFemale = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        CMBEducationState = new javax.swing.JComboBox<>();
        BTID = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtRegId = new javax.swing.JTextField();
        TxtRegFee = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dateChooserRegDate = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        courseCmb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtBatch = new javax.swing.JTextField();
        TxtStartDate = new javax.swing.JTextField();
        TxtCourseId = new javax.swing.JTextField();
        TxtDuration = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jPanel3.setBackground(java.awt.Color.darkGray);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATION");

        HOME_TIME1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME1.setForeground(new java.awt.Color(255, 255, 255));

        HOME_TIME.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        HOME_TIME.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME_TIME1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HOME_TIME1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(HOME_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Details");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Id");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Name With Initial");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Full Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 88, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("DOB");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 175, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("NIC");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 42, -1, -1));

        TxtStudentId.setEditable(false);
        TxtStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStudentIdActionPerformed(evt);
            }
        });
        jPanel4.add(TxtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 33, 461, -1));

        TxtStudentAddress.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtStudentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStudentAddressActionPerformed(evt);
            }
        });
        jPanel4.add(TxtStudentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 125, 461, -1));

        TxtStudentNameWithInitial.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtStudentNameWithInitial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtStudentNameWithInitialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtStudentNameWithInitialKeyReleased(evt);
            }
        });
        jPanel4.add(TxtStudentNameWithInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 79, 461, -1));

        TxtStudentNic.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtStudentNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtStudentNicKeyPressed(evt);
            }
        });
        jPanel4.add(TxtStudentNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 33, 516, -1));

        TxtStudentFullName.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtStudentFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtStudentFullNameKeyReleased(evt);
            }
        });
        jPanel4.add(TxtStudentFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 79, 516, -1));

        DateChooserStudentDOB.setCalendarBackground(new java.awt.Color(0, 0, 0));
        DateChooserStudentDOB.setCalendarPreferredSize(new java.awt.Dimension(330, 330));
        jPanel4.add(DateChooserStudentDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 171, 331, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel21.setText("Telephone");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 129, -1, -1));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setText("Gender");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel23.setText("School/Univercity");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, -1, -1));

        TxtStudentSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStudentSchoolActionPerformed(evt);
            }
        });
        jPanel4.add(TxtStudentSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 171, 461, -1));

        TxtStudentTel.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtStudentTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStudentTelActionPerformed(evt);
            }
        });
        jPanel4.add(TxtStudentTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 125, 516, -1));

        buttonGroup1.add(RadioMale);
        RadioMale.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RadioMale.setText("Male");
        RadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMaleActionPerformed(evt);
            }
        });
        jPanel4.add(RadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 222, -1, -1));

        buttonGroup1.add(RadioFemale);
        RadioFemale.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RadioFemale.setText("Female");
        jPanel4.add(RadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 222, -1, -1));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel24.setText("Education State");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 222, -1, -1));

        CMBEducationState.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        CMBEducationState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master", "Degree", "Diploma", "A/L", "O/L", "Other" }));
        CMBEducationState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBEducationStateActionPerformed(evt);
            }
        });
        jPanel4.add(CMBEducationState, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 217, 185, -1));

        BTID.setForeground(new java.awt.Color(204, 102, 255));
        jPanel4.add(BTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 217, 34, 29));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 180, 250));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel15.setText("jLabel14");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 250));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel25.setText("jLabel14");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 240));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel26.setText("jLabel14");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Registration Details");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel18.setText("Registration Id");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel20.setText("Reg Date");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 44, -1, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel19.setText("Reg Fee");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 44, -1, -1));

        TxtRegId.setEditable(false);
        TxtRegId.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel5.add(TxtRegId, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 40, 340, -1));

        TxtRegFee.setMinimumSize(new java.awt.Dimension(6, 30));
        TxtRegFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRegFeeActionPerformed(evt);
            }
        });
        jPanel5.add(TxtRegFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 40, 311, -1));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 111, 132, 45));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 111, 131, 45));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("Batch Transfer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 111, -1, 45));

        dateChooserRegDate.setEditable(false);
        jPanel5.add(dateChooserRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 40, 351, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel31.setText("jLabel14");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 160));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel32.setText("jLabel14");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 180, 160));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel30.setText("jLabel14");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 160));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1342, 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Course Details");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        courseCmb.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        courseCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseCmbItemStateChanged(evt);
            }
        });
        courseCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCmbActionPerformed(evt);
            }
        });
        jPanel7.add(courseCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 529, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Course Name");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setText("Batch");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setText("Start Date");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, -1, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setText("Course Id");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setText("Duration");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 91, -1, -1));

        TxtBatch.setEditable(false);
        TxtBatch.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel7.add(TxtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, 529, -1));

        TxtStartDate.setEditable(false);
        TxtStartDate.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel7.add(TxtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 133, 529, -1));

        TxtCourseId.setEditable(false);
        TxtCourseId.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel7.add(TxtCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 41, 502, -1));

        TxtDuration.setEditable(false);
        TxtDuration.setMinimumSize(new java.awt.Dimension(6, 30));
        jPanel7.add(TxtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 87, 502, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel29.setText("jLabel14");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 180, 180));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel27.setText("jLabel14");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 180));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/edu/ijse/Images/seamless-white-pattern-background-vector-id508007780.jpg"))); // NOI18N
        jLabel28.setText("jLabel14");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        StudentDTO studentDTO = new StudentDTO(TxtStudentId.getText(), TxtStudentNic.getText(), TxtStudentNameWithInitial.getText(), TxtStudentFullName.getText(), TxtStudentAddress.getText(), TxtStudentTel.getText(), TxtStudentSchool.getText(), DateChooserStudentDOB.getText(), buttonGroup1.getSelection().getActionCommand(), (String) CMBEducationState.getSelectedItem());
        RegistrationDTO registrationDTO = new RegistrationDTO(TxtRegId.getText(), TxtStudentId.getText(), iid, TxtRegFee.getText(), dateChooserRegDate.getText());

        try {
            boolean saveStudent = registrationController.saveStudent(studentDTO, registrationDTO);
            if (saveStudent) {
                System.out.println("ok");
                JOptionPane.showMessageDialog(rootPane, "Added Succes");
                collectingBills();

                jasperReport();
                clearTxt();
            } else {
                System.out.println("no");
                JOptionPane.showMessageDialog(rootPane, "Not Add");
            }
        } catch (Exception ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentIdActionPerformed

    private void TxtStudentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStudentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentAddressActionPerformed

    private void TxtStudentSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStudentSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentSchoolActionPerformed

    private void TxtStudentTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStudentTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentTelActionPerformed

    private void RadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioMaleActionPerformed

    private void CMBEducationStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBEducationStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBEducationStateActionPerformed

    private void courseCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseCmbItemStateChanged
        comboChange();
    }//GEN-LAST:event_courseCmbItemStateChanged

    private void courseCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCmbActionPerformed
        comboChange();        // TODO add your handling code here:
    }//GEN-LAST:event_courseCmbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BatchTransfer batchTransfer = new BatchTransfer();
        batchTransfer.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtRegFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegFeeActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegFeeActionPerformed

    private void TxtStudentFullNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStudentFullNameKeyReleased
     // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentFullNameKeyReleased

    private void TxtStudentNameWithInitialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStudentNameWithInitialKeyReleased
     // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentNameWithInitialKeyReleased

    private void TxtStudentNicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStudentNicKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentNicKeyPressed

    private void TxtStudentNameWithInitialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStudentNameWithInitialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudentNameWithInitialKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTID;
    private javax.swing.JComboBox<String> CMBEducationState;
    private datechooser.beans.DateChooserCombo DateChooserStudentDOB;
    private javax.swing.JLabel HOME_TIME;
    private javax.swing.JLabel HOME_TIME1;
    private javax.swing.JRadioButton RadioFemale;
    private javax.swing.JRadioButton RadioMale;
    private javax.swing.JTextField TxtBatch;
    private javax.swing.JTextField TxtCourseId;
    private javax.swing.JTextField TxtDuration;
    private javax.swing.JTextField TxtRegFee;
    private javax.swing.JTextField TxtRegId;
    private javax.swing.JTextField TxtStartDate;
    private javax.swing.JTextField TxtStudentAddress;
    private javax.swing.JTextField TxtStudentFullName;
    private javax.swing.JTextField TxtStudentId;
    private javax.swing.JTextField TxtStudentNameWithInitial;
    private javax.swing.JTextField TxtStudentNic;
    private javax.swing.JTextField TxtStudentSchool;
    private javax.swing.JTextField TxtStudentTel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> courseCmb;
    private javax.swing.JTextField dateChooserRegDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String currentdate = new SimpleDateFormat("hh:mm:aa").format(date);
                    HOME_TIME.setText(currentdate);

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        HOME_TIME1.setText(s.format(d));
        dateChooserRegDate.setText(s.format(d));

    }

    private void loadCombo() {
        try {
            ArrayList<BatchDTO> SearchAll = batchController.SearchAll();
            if (SearchAll != null) {

                for (BatchDTO batchDTO : SearchAll) {

                    if (batchDTO.getBatchState().equals("End")) {

                    } else {
                        courseCmb.addItem(batchDTO.getBatch());
                    }

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCombo2() {
        try {
            ArrayList<CourseDTO> SearchAll = courseController.SearchAll();
            if (SearchAll != null) {

                for (CourseDTO courseDTO : SearchAll) {

                    courseCmb.addItem(courseDTO.getCoursename());

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void comboChange() {
        try {
            CourseDTO SearchAllAndShort = courseController.SearchAllAndShort((String) courseCmb.getSelectedItem());
            if (SearchAllAndShort != null) {
                ArrayList<BatchDTO> SearchAllAndShort1 = batchController.SearchAll1(SearchAllAndShort.getCid());
                if (SearchAllAndShort1 != null) {
                    for (BatchDTO batchDTO : SearchAllAndShort1) {
                        if (batchDTO.getBatchState().equals("New")) {
                            TxtBatch.setText(batchDTO.getBatch());
                            iid = batchDTO.getBid();
                            TxtStartDate.setText(batchDTO.getStartDate());
                            TxtDuration.setText(SearchAllAndShort.getDuration());

                            TxtCourseId.setText(SearchAllAndShort.getCid());
//                    
                        } else {
                            System.out.println("sort 1 null");
                        }
                    }
                }
            } else {
                System.out.println("sort 2 null");
            }
        } catch (Exception ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Radio() {
        RadioMale.setActionCommand("Male");
        RadioFemale.setActionCommand("FeMale");
    }

    private void Idgent() {
        tableName = "Student";
        columName = "sid";
        prefix = "S";
        TxtStudentId.setText(IDGenarator.getNextIdGenaretor(tableName, columName, prefix));

    }

    private void Idgent1() {
        tableName1 = "registration";
        columName1 = "rid";
        prefix1 = "R";
        TxtRegId.setText(IDGenarator.getNextIdGenaretor(tableName1, columName1, prefix1));

    }

    private void jasperReport() {

        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(StartUp.class.getResourceAsStream("/lk//edu//ijse//Reports/RegistrationGetUI_1.jasper"));

            HashMap<String, Object> parHashMap = new HashMap<>();
            parHashMap.put("SID", TxtStudentId.getText());
            parHashMap.put("NwithInit", TxtStudentNic.getText());
            parHashMap.put("FullName", TxtStudentNameWithInitial.getText());
            parHashMap.put("Nic", TxtStudentFullName.getText());
            parHashMap.put("Address", TxtStudentAddress.getText());
            parHashMap.put("Telephone", TxtStudentTel.getText());
            parHashMap.put("Scl", TxtStudentSchool.getText());
            parHashMap.put("DOB", DateChooserStudentDOB.getText());
            parHashMap.put("Gender", buttonGroup1.getSelection().getActionCommand());
            parHashMap.put("EduState", CMBEducationState.getSelectedItem());

            parHashMap.put("CName", courseCmb.getSelectedItem());
            parHashMap.put("CourseID", TxtCourseId.getText());
            parHashMap.put("Batch", TxtBatch.getText());
            parHashMap.put("Duration", TxtDuration.getText());
            parHashMap.put("StartDate", TxtStartDate.getText());

            parHashMap.put("RID", TxtRegId.getText());
            parHashMap.put("RFEE", TxtRegFee.getText());
            parHashMap.put("RDate", dateChooserRegDate.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parHashMap, new JREmptyDataSource());
            JasperViewer jasperViewer = new JasperViewer(jasperPrint);
            java.awt.Container container = jasperViewer.getContentPane();

            JDialog jDialog = new JDialog();
            jDialog.setContentPane(container);
            jDialog.setSize(jasperViewer.getSize());
            jDialog.setLocationRelativeTo(null);
            jDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  

    private void clearTxt() {
        TxtStudentId.setText("");
        TxtStudentNic.setText("");
        TxtStudentNameWithInitial.setText("");
        TxtStudentFullName.setText("");
        TxtStudentAddress.setText("");
        TxtStudentTel.setText("");
        TxtStudentSchool.setText("");
        TxtRegId.setText("");
        TxtStudentId.setText("");
//        dateChooserRegDate.setText("");
        Idgent();
        Idgent1();
        TxtRegFee.setText("");
    }
    private void collectingBills(){
    DailycollectionDTO dailycollectionDTO = new DailycollectionDTO(0,"Registration",TxtBatch.getText(), HOME_TIME1.getText(), TxtRegFee.getText());

        try {
            boolean add = dailyCollectionController.add(dailycollectionDTO);
            if (add) {
                System.out.println(" Add Ok");
//                JOptionPane.showMessageDialog(rootPane, "afsdsdfasdfasf");
            } else {
                System.out.println(" Not Add");
//                JOptionPane.showMessageDialog(rootPane, "aefdadsf");
            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrationWithPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
}

}

